=== IDgis/deegree3/deegree-core/src/main/resources/META-INF/schemas/datasource/0.5.0/feature/simplesql.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!--
  This file is part of deegree, for copyright/license information, please visit http://www.deegree.org/license.
-->
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.deegree.org/datasource/feature/simplesql" elementFormDefault="qualified"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.feature.persistence.simplesql.jaxb" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>
  <element name="SimpleSQLFeatureStore">
    <annotation>
      <documentation>SQL FeatureStore that is configured by an SQL statement/connection.</documentation>
      <appinfo>
        <jaxb:class name="SimpleSQLFeatureStoreConfig" />
      </appinfo>      
    </annotation>
    <complexType>
      <sequence>
        <element name="StorageSRS" type="string" />
        <element name="ConnectionPoolId" type="string" />
        <element name="SQLStatement" type="string" />
        <element name="BBoxStatement" type="string" />
        <element name="LODStatement" minOccurs="0" maxOccurs="unbounded">
          <complexType>
            <simpleContent>
              <extension base="string">
                <attribute name="aboveScale" type="int" />
              </extension>
            </simpleContent>
          </complexType>
        </element>
        <element name="Namespace" type="string" minOccurs="0" />
        <element name="FeatureTypeName" type="string" minOccurs="0" />
      </sequence>
      <attribute name="configVersion" use="required" fixed="0.5.0" />
    </complexType>
  </element>
</schema>

=== IDgis/deegree3/deegree-core/src/main/resources/META-INF/schemas/datasource/0.5.0/feature/example_simplesql.xml
<SimpleSQLFeatureStore configVersion="0.5.0" xmlns="http://www.deegree.org/datasource/feature/simplesql"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.deegree.org/datasource/feature/simplesql http://schemas.deegree.org/datasource/0.5.0/feature/simplesql.xsd">

  <!-- [1] CRS for storing geometries -->
  <StorageSRS>EPSG:4326</StorageSRS>

  <!-- [1] database connection -->
  <ConnectionPoolId>connid</ConnectionPoolId>
  
  <!-- [1] query statement -->
  <SQLStatement>
            SELECT name, title, asbinary(the_geom) FROM some_table
            WHERE the_geom &amp;&amp; st_geomfromtext(?, -1)
  </SQLStatement>
  
  <!-- [1] bounding box statement -->
  <BBoxStatement>SELECT astext(ST_Estimated_Extent('some_table', 'the_geom')) as bbox</BBoxStatement>
  
  <!-- [0..n] different statements for specific WMS scale ranges -->
  <LODStatement aboveScale="3000">
            SELECT name, title, asbinary(st_simplifypreservetopology(the_geom, 1)) FROM some_table
            WHERE the_geom &amp;&amp; st_geomfromtext(?, -1)
  </LODStatement>
  <LODStatement aboveScale="6000">
            SELECT name, title, asbinary(st_simplify(the_geom, 30)) FROM some_table
            WHERE the_geom &amp;&amp; st_geomfromtext(?, -1) and not st_isempty(st_simplify(the_geom, 30))
  </LODStatement>

  <!-- [0..1] target namespace -->
  <Namespace>http://www.deegree.org/app</Namespace>

</SimpleSQLFeatureStore>
